#!/bin/bash -ex

DOCKER_ARCH=${BUILD_ARCH:-amd64}
DOCKER_ORG=samip537
DOCKER_IMAGE=pdns-slave:${DOCKER_ARCH}

if [ $DOCKER_ARCH = "arm32v6" ]; then
	docker build --build-arg ARCH=${DOCKER_ARCH} \
        -t $DOCKER_ORG/$DOCKER_IMAGE \
        -f Dockerfile.arm32v6 .
fi

if [ $DOCKER_ARCH = "arm32v7" ]; then
        docker build --build-arg ARCH=${DOCKER_ARCH} \
        -t $DOCKER_ORG/$DOCKER_IMAGE \
        -f Dockerfile.arm32v6 .
fi

if [ $DOCKER_ARCH = "arm64v8" ]; then
        docker build --build-arg ARCH=${DOCKER_ARCH} \
        -t $DOCKER_ORG/$DOCKER_IMAGE \
        -f Dockerfile.arm64 .
fi


if [ $DOCKER_ARCH = "amd64" ]; then
        docker build --build-arg ARCH=${DOCKER_ARCH} \
        -t $DOCKER_ORG/$DOCKER_IMAGE \
        -f Dockerfile .
fi
